items:
- name: Ansible en la documentación de Azure
  href: ./index.yml
- name: Información general
  items:
  - name: Acerca de Ansible en Azure
    href: ./ansible-overview.md
- name: Guías de inicio rápido
  items:
  - name: Instalación de Ansible en una máquina virtual Linux
    href: /azure/virtual-machines/linux/ansible-install-configure
    maintainContext: true
  - name: Creación de una máquina virtual Linux
    href: /azure/virtual-machines/linux/ansible-create-vm
    maintainContext: true
  - name: Administración de una máquina virtual Linux
    href: /azure/virtual-machines/linux/ansible-manage-linux-vm
    maintainContext: true
  expanded: true
- name: Tutoriales
  items:
  - name: Ejecución de un guión de procedimientos en Cloud Shell
    href: ./ansible-run-playbook-in-cloudshell.md
    maintainContext: true
  - name: Administración de inventarios dinámicos
    href: ./ansible-manage-azure-dynamic-inventories.md
    maintainContext: true
  - name: Creación y configuración de VMSS
    href: ./ansible-create-configure-vmss.md
  - name: Implementación de aplicación en VMSS
    href: ./ansible-deploy-app-vmss.md
  - name: Creación y configuración de clústeres AKS
    href: ./ansible-create-configure-aks.md
  - name: Creación y configuración de una instancia de Azure Application Gateway
    href: ./ansible-create-configure-application-gateway.md
  - name: Creación y configuración de Azure DB for MySQL
    href: ./ansible-create-configure-mysql.md
  - name: Creación y configuración de instancias de Azure Web Apps
    href: ./ansible-create-configure-azure-web-apps.md
  - name: Escalado de Azure Web Apps
    href: ./ansible-scale-azure-web-apps.md
- name: Referencia
  items:
  - name: Roles de guión de procedimientos
    items:
    - name: azure_module
      href: https://galaxy.ansible.com/Azure/azure_modules/
    - name: azure_preview_module
      href: https://galaxy.ansible.com/Azure/azure_preview_modules
  - name: Versiones y características
    href: ./ansible-matrix.md
  - name: Azure Container Instances
    href: https://docs.ansible.com/ansible/latest/azure_rm_containerinstance_module.html
  - name: Azure Functions
    href: https://docs.ansible.com/ansible/latest/azure_rm_functionapp_module.html
  - name: Equilibradores de carga
    href: https://docs.ansible.com/ansible/latest/azure_rm_loadbalancer_module.html
  - name: Máquinas virtuales
    href: https://docs.ansible.com/ansible/latest/azure_rm_virtualmachine_module.html
  - name: Todos los módulos de Azure
    href: https://docs.ansible.com/ansible/latest/list_of_cloud_modules.html#azure
- name: Herramientas
  items:
  - name: Extensión de Visual Studio Code para Ansible
    href: https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible
ms.openlocfilehash: 6e4a972588a63a5ce028a3e1f7a868565bbabbf7
ms.sourcegitcommit: efcd039e5e3de3149c9de7296c57566e0f88b106
ms.translationtype: HT
ms.contentlocale: es-ES
ms.lasthandoff: 12/10/2018
ms.locfileid: "53164669"
