items:
- name: Ansible en la documentación de Azure
  href: ./index.yml
- name: Información general
  items:
  - name: Acerca de Ansible en Azure
    href: ./ansible-overview.md
- name: Guías de inicio rápido
  items:
  - name: Instalación de Ansible en una máquina virtual Linux
    href: /azure/virtual-machines/linux/ansible-install-configure
    maintainContext: true
  - name: Creación de una máquina virtual Linux
    href: /azure/virtual-machines/linux/ansible-create-vm
    maintainContext: true
  - name: Administración de una máquina virtual Linux
    href: /azure/virtual-machines/linux/ansible-manage-linux-vm
    maintainContext: true
  expanded: true
- name: Tutoriales
  items:
  - name: Ejecución de un guión de procedimientos en Cloud Shell
    href: ./ansible-run-playbook-in-cloudshell.md
    maintainContext: true
  - name: Administración de inventarios dinámicos
    href: ./ansible-manage-azure-dynamic-inventories.md
    maintainContext: true
  - name: Creación y configuración de VMSS
    href: ./ansible-create-configure-vmss.md
  - name: Implementación de aplicación en VMSS
    href: ./ansible-deploy-app-vmss.md
  - name: Creación y configuración de clústeres AKS
    href: ./ansible-create-configure-aks.md
- name: Referencia
  items:
  - name: Roles de guión de procedimientos
    items:
    - name: azure_module
      href: https://galaxy.ansible.com/Azure/azure_modules/
    - name: azure_preview_module
      href: https://galaxy.ansible.com/Azure/azure_preview_modules
  - name: Versiones y características
    href: ./ansible-matrix.md
  - name: Azure Container Instances
    href: http://docs.ansible.com/ansible/latest/azure_rm_containerinstance_module.html
  - name: Azure Functions
    href: http://docs.ansible.com/ansible/latest/azure_rm_functionapp_module.html
  - name: Equilibradores de carga
    href: http://docs.ansible.com/ansible/latest/azure_rm_loadbalancer_module.html
  - name: Máquinas virtuales
    href: http://docs.ansible.com/ansible/latest/azure_rm_virtualmachine_module.html
  - name: Todos los módulos de Azure
    href: http://docs.ansible.com/ansible/latest/list_of_cloud_modules.html#azure
- name: Herramientas
  items:
  - name: Extensión de Visual Studio Code para Ansible
    href: https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible
ms.openlocfilehash: c6f8b3fe0267cd011ee5c6d7919f0942209aa38d
ms.sourcegitcommit: 31241b7ef35c37749b4261644adf1f5a029b2b8e
ms.translationtype: HT
ms.contentlocale: es-ES
ms.lasthandoff: 09/04/2018
ms.locfileid: "43667471"
